<?php
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
module_load_include('inc', 'incrwd', 'incrwd_utils');
module_load_include('inc', 'incrwd', 'incrwd_api');

define('INCRWD_DEBUG', False);

function incrwd_help($path, $arg) {
  switch ($path) {
    case "admin/help#incrwd":
      return '<p>'.  t("Add the incrwd snippets and reward/badge enables the comments") .'</p>';
      break;
  }
}

function incrwd_footer($main=0) {
  if (variable_get('incrwd_enable_rewards', null)) {
    $script = 'var _icq = _icq || [];';
    $script .= 'var incrwd_config = {';
    $script .= '  site_id: ' . variable_get('incrwd_id', 0) . ',';
    //$script .= '  remote_auth: "' . incrwd_sso() . '",';
    $script .= '};';
    if (!INCRWD_DEBUG) {
      $script .= '(function() {';
      $script .= '  var ic = document.createElement("script"); ic.type = "text/javascript"; ic.async = true;';
      $script .= '  ic.src = "http://static.widget.myincrwd.com/incrwd.js";';
      $script .= '  var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ic, s);';
      $script .= '})();';
    } else {
      $script .= 'document.write(unescape("%3Cscript src=\'http://incrwd.example.com:8000/w/bootloader.js\' type=\'text/javascript\'%3E%3C/script%3E"));';
    }
    drupal_add_js($script, 'inline', 'footer');
  }
}

function incrwd_menu() {
  $items = array();
  $items['admin/settings/incrwd'] = array(
    'title' => 'Incrwd',
    'description' => 'Configuration of incrwd rewards/achievement settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('incrwd_form'),
    'access arguments' => array('access administration incrwd'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function incrwd_form() {
  $form['incrwd_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Id'),
    '#default_value' => variable_get('incrwd_id', ''),
    '#size' => 127,
    '#maxlength' => 127,
    '#description' => t('The id you got from http://www.incrwd.com.'),
    '#required' => TRUE,
  );

  $form['incrwd_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Secret Key'),
    '#default_value' => variable_get('incrwd_key', ''),
    '#size' => 127,
    '#maxlength' => 127,
    '#description' => t('The key you got from http://www.incrwd.com.'),
    '#required' => TRUE,
  );

  $form['incrwd_enable_rewards'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable rewards'),
    '#default_value' => variable_get('incrwd_enable_rewards', false),
    '#description' => t('Enables the loyalty program.'),
  );

  return system_settings_form($form);
}

function incrwd_get_api() {
  return new IncrwdApi(
    variable_get('incrwd_id', ''),
    variable_get('incrwd_key', ''),
    INCRWD_DEBUG ? 'http://incrwd.example.com/w/api/' : 'http://widget.myincrwd.com/w/api/');
}

function incrwd_comment(&$comment, $op) {
  if ($op == 'insert') {
    $api = incrwd_get_api();
    $api->inserted_comment($comment['cid']);    
  } else if ($op == 'publish') {
    $api = incrwd_get_api();
    $api->published_comment($comment->cid);
  }
}
